version: '3'
services:
  backend:
    build:
      context: ./back 
      dockerfile: Dockerfile      
    ports:
      - "3000:3000"               
   

  frontend:
    build:
      context: ./front  
      dockerfile: Dockerfile        
    ports:
      - "80:80"                 

  database:
    
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=dockerFullStack
    ports:
      - "5432:5432"
