version: '3'
services:
  backend:
    build:
      context: ./back 
      dockerfile: Dockerfile      
    ports:
      - "3000:3000"               

  frontend:
    build:
      context: ./front  
      dockerfile: Dockerfile        
    ports:
      - "80:3000"                 

  database:
    image: mysql:latest            
    
    ports:
      - "3306:3306"                
